// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MutationReply struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MutationReply) Reset()         { *m = MutationReply{} }
func (m *MutationReply) String() string { return proto.CompactTextString(m) }
func (*MutationReply) ProtoMessage()    {}
func (*MutationReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *MutationReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutationReply.Unmarshal(m, b)
}
func (m *MutationReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutationReply.Marshal(b, m, deterministic)
}
func (m *MutationReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutationReply.Merge(m, src)
}
func (m *MutationReply) XXX_Size() int {
	return xxx_messageInfo_MutationReply.Size(m)
}
func (m *MutationReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MutationReply.DiscardUnknown(m)
}

var xxx_messageInfo_MutationReply proto.InternalMessageInfo

func (m *MutationReply) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            int64    `protobuf:"varint,15,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type Token struct {
	AccessToken          string               `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	ExpiresIn            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=expiresIn,proto3" json:"expiresIn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Token) GetExpiresIn() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiresIn
	}
	return nil
}

type LoginRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginReply struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type ProfileReply struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	PostCount            int32    `protobuf:"varint,2,opt,name=postCount,proto3" json:"postCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileReply) Reset()         { *m = ProfileReply{} }
func (m *ProfileReply) String() string { return proto.CompactTextString(m) }
func (*ProfileReply) ProtoMessage()    {}
func (*ProfileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *ProfileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileReply.Unmarshal(m, b)
}
func (m *ProfileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileReply.Marshal(b, m, deterministic)
}
func (m *ProfileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileReply.Merge(m, src)
}
func (m *ProfileReply) XXX_Size() int {
	return xxx_messageInfo_ProfileReply.Size(m)
}
func (m *ProfileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileReply proto.InternalMessageInfo

func (m *ProfileReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ProfileReply) GetPostCount() int32 {
	if m != nil {
		return m.PostCount
	}
	return 0
}

func init() {
	proto.RegisterType((*MutationReply)(nil), "user.MutationReply")
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*Token)(nil), "user.Token")
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "user.LoginReply")
	proto.RegisterType((*ProfileReply)(nil), "user.ProfileReply")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0xcd, 0x6e, 0xd4, 0x30,
	0x18, 0x54, 0x96, 0xdd, 0x42, 0xbe, 0x94, 0x05, 0x2c, 0x54, 0xad, 0x42, 0x81, 0xc5, 0x17, 0x2a,
	0x0e, 0x89, 0x58, 0x2e, 0x88, 0x1b, 0xad, 0x90, 0x8a, 0x54, 0xa4, 0x95, 0x29, 0x0f, 0xe0, 0x66,
	0xbf, 0x46, 0x16, 0x89, 0x6d, 0x6c, 0xa7, 0x62, 0xaf, 0xbc, 0x02, 0x57, 0xde, 0x8a, 0x57, 0xe0,
	0x41, 0x90, 0x7f, 0xda, 0x2c, 0xf4, 0x66, 0xcf, 0xcc, 0x37, 0x9a, 0xf9, 0x6c, 0x80, 0xc1, 0xa2,
	0xa9, 0xb4, 0x51, 0x4e, 0x91, 0xa9, 0x3f, 0x97, 0x4f, 0x5a, 0xa5, 0xda, 0x0e, 0xeb, 0x80, 0x5d,
	0x0c, 0x97, 0x35, 0xf6, 0xda, 0x6d, 0xa3, 0xa4, 0x7c, 0xfe, 0x3f, 0xe9, 0x44, 0x8f, 0xd6, 0xf1,
	0x5e, 0x27, 0xc1, 0x61, 0x12, 0x70, 0x2d, 0x6a, 0x2e, 0xa5, 0x72, 0xdc, 0x09, 0x25, 0x6d, 0x64,
	0xe9, 0x4b, 0xb8, 0xff, 0x69, 0x88, 0x10, 0x43, 0xdd, 0x6d, 0xc9, 0x01, 0xec, 0x19, 0xb4, 0x43,
	0xe7, 0x16, 0xd9, 0x32, 0x3b, 0xba, 0xc7, 0xd2, 0x8d, 0x9e, 0xc2, 0xf4, 0x8b, 0x45, 0x43, 0xe6,
	0x30, 0x11, 0x9b, 0xc0, 0xe5, 0x6c, 0x22, 0x36, 0x84, 0xc0, 0x54, 0xf2, 0x1e, 0x17, 0x93, 0x80,
	0x84, 0x33, 0x39, 0x84, 0xbc, 0x31, 0xc8, 0x1d, 0x6e, 0xde, 0xbb, 0xc5, 0x83, 0x65, 0x76, 0x74,
	0x87, 0x8d, 0x00, 0x6d, 0x60, 0x76, 0xae, 0xbe, 0xa2, 0x24, 0x4b, 0x28, 0x78, 0xd3, 0xa0, 0xb5,
	0xe1, 0x9a, 0x3c, 0x77, 0x21, 0xf2, 0x16, 0x72, 0xfc, 0xae, 0x85, 0x41, 0xfb, 0x51, 0x06, 0xa3,
	0x62, 0x55, 0x56, 0xb1, 0x4f, 0x75, 0x5d, 0xb8, 0x3a, 0xbf, 0x2e, 0xcc, 0x46, 0x31, 0xa5, 0xb0,
	0x7f, 0xa6, 0x5a, 0x21, 0x19, 0x7e, 0x1b, 0xd0, 0xba, 0x9b, 0x98, 0xd9, 0x18, 0x93, 0xd6, 0x00,
	0x49, 0xe3, 0x8b, 0xbf, 0x80, 0x99, 0xbb, 0xc9, 0x51, 0xac, 0x8a, 0x2a, 0xbc, 0x43, 0xc8, 0xc1,
	0x22, 0x43, 0xcf, 0x60, 0x7f, 0x6d, 0xd4, 0xa5, 0xe8, 0x30, 0x8e, 0x3c, 0x83, 0xf0, 0x40, 0x69,
	0x02, 0xe2, 0x84, 0xdf, 0x12, 0x0b, 0xb8, 0xdf, 0x83, 0x56, 0xd6, 0x9d, 0xa8, 0x41, 0xba, 0xb0,
	0xa0, 0x19, 0x1b, 0x81, 0xd5, 0xaf, 0x0c, 0x0a, 0x2f, 0xfe, 0x8c, 0xe6, 0x4a, 0x34, 0x48, 0x4e,
	0x60, 0x16, 0xe2, 0x10, 0x12, 0x8d, 0x76, 0xf3, 0x97, 0x0f, 0xff, 0xc1, 0x74, 0xb7, 0xa5, 0x8f,
	0x7f, 0xfc, 0xfe, 0xf3, 0x73, 0x32, 0xa7, 0x79, 0x7d, 0xf5, 0xba, 0xf6, 0xa4, 0x7d, 0x97, 0xbd,
	0x22, 0xa7, 0x70, 0x37, 0x45, 0x24, 0x07, 0xb7, 0x36, 0xf5, 0xc1, 0xff, 0x9b, 0x32, 0xd9, 0xef,
	0x36, 0xa1, 0x8f, 0x82, 0x59, 0x41, 0x46, 0xb3, 0xe3, 0xa7, 0x30, 0x6f, 0x54, 0xd5, 0x5a, 0xc7,
	0xf9, 0x26, 0x4c, 0x1c, 0xe7, 0x3e, 0xed, 0xda, 0x9b, 0xad, 0xb3, 0x8b, 0xbd, 0xe0, 0xfa, 0xe6,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x95, 0x4d, 0x37, 0x65, 0xaf, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	Profile(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ProfileReply, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/user.UserService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Profile(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ProfileReply, error) {
	out := new(ProfileReply)
	err := c.cc.Invoke(ctx, "/user.UserService/Profile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	Profile(context.Context, *empty.Empty) (*ProfileReply, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Profile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Profile(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "Profile",
			Handler:    _UserService_Profile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
